apiVersion: v1
kind: Service
metadata:
  name: cv-nextgen
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cv-nextgen.labels" . | nindent 4 }}
spec:
  ports:
    - name: cv
      port: {{.Values.service.port}}
      protocol: TCP
      targetPort: {{.Values.service.port}}
    - name: grpc-cv-nextgen
      port: {{.Values.service.grpcport}}
      protocol: TCP
      targetPort: {{.Values.service.grpcport}}
  selector:
    {{- include "cv-nextgen.selectorLabels" . | nindent 4 }}
  type: {{.Values.service.type}}